### ISSUE TITLE
Make the footer on home page responsive

### ISSUE THREAD

**Issue by imabhinavagarwal** [imabhinavagarwal/ComponentLibrary#19]
The footer should stick to bottom of screen for all screen sizes

**Comment by imanpalsingh** [comment]
Hey ! Can I pick this up?

**Comment by imabhinavagarwal** [comment]
Sure. Please go thru contributing file and feel free to add yourself in contributors file if you want to actively keep contributing.

**Comment by imanpalsingh** [comment]
Please check https://github.com/imabhinavagarwal/ComponentLibrary/pull/20 have posted a question as well.
