### ISSUE TITLE
Add spinner/loader component

### ISSUE THREAD

**Issue by imabhinavagarwal** [imabhinavagarwal/ComponentLibrary#28]

**Comment by flow6979** [comment]
hey @imabhinavagarwal can i contribute to this issue?

**Comment by imabhinavagarwal** [comment]
Sure

**Comment by flow6979** [comment]
bro @imabhinavagarwal , this man not even commented and added a pull request bu copying some code. can you please close his PR as you have assigned this to me

**Comment by imabhinavagarwal** [comment]
Sure @flow6979
