### ISSUE TITLE
Add navbar component

### ISSUE THREAD

**Issue by imabhinavagarwal** [imabhinavagarwal/ComponentLibrary#29]

**Comment by flow6979** [comment]
can i work on this issue?

**Comment by sumit-022** [comment]
I want to work on this

**Comment by Abhishekvermaa** [comment]
pls assign this issue to me @imabhinavagarwal

**Comment by imabhinavagarwal** [comment]
Sorry @sumit-022 @Abhishekvermaa  but I cannot re-assign until @flow6979  decides to drop it

**Comment by flow6979** [comment]
> Sorry @sumit-022 @Abhishekvermaa but I cannot re-assign until @flow6979 decides to drop it

i'll do it sirrr
