### ISSUE TITLE
Changes in Nav Bar and Components page

### ISSUE THREAD

**Issue by Yashh-Bajaj** [imabhinavagarwal/ComponentLibrary#39]
I can improve nav bar and can make several changes like style changing using different gradient or solid pattern colours and making the easy style center of attraction and attractive. Making Easy style more bolder .
Screenshot-
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/97032507/194008006-8ef8f1b9-3096-481e-a595-be864a8cc998.png">

Changing the font of components page and making some more changes will make it more attractive.
Screenshot-
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/97032507/194008081-f20086c4-6c03-4a1f-b31b-084f314674b4.png">
So can I work on this under Hacktoberfest 2022.

**Comment by imabhinavagarwal** [comment]
@Yashh-Bajaj The initial goal is to add as many components to the library as possible. Once that is done, we can look for revamp but doing it now won't make much sense

**Comment by ompanchwate** [comment]
Hello, Can you assign me with this issue under Hacktoberfest 2022. I can add more Components like Modals, Drop downs, Input field and many more and also modify User Interface to make it more attractive and user friendly.
