### ISSUE TITLE
Coloured Components

### ISSUE THREAD

**Issue by Yashh-Bajaj** [imabhinavagarwal/ComponentLibrary#40]
We can add different components to the library by adding different colours like red blue green in pagination section, different colours in loader section like red loader blue loader, we can add different colours to the buttons like red blue green colour.
I will be greatful if you will give this chance to me for hacktoberfest.

**Comment by imabhinavagarwal** [comment]
Ref this : https://github.com/imabhinavagarwal/ComponentLibrary/issues/39#issuecomment-1268294476
